version: "3.9"
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "final_project"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - .:/POSTGRES_DBpip
